/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/fakecall`; params?: Router.UnknownInputParams; } | { pathname: `/app/home`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app/login`; params?: Router.UnknownInputParams; } | { pathname: `/app/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/app/profile`; params?: Router.UnknownInputParams; } | { pathname: `/app/safetytips`; params?: Router.UnknownInputParams; } | { pathname: `/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/app/sos`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip1`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip2`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip3`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip4`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip5`; params?: Router.UnknownInputParams; } | { pathname: `/app/constants/ThemeContext`; params?: Router.UnknownInputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/app/fakecall`; params?: Router.UnknownOutputParams; } | { pathname: `/app/home`; params?: Router.UnknownOutputParams; } | { pathname: `/app`; params?: Router.UnknownOutputParams; } | { pathname: `/app/login`; params?: Router.UnknownOutputParams; } | { pathname: `/app/navigation`; params?: Router.UnknownOutputParams; } | { pathname: `/app/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/app/safetytips`; params?: Router.UnknownOutputParams; } | { pathname: `/app/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/app/sos`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tip1`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tip2`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tip3`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tip4`; params?: Router.UnknownOutputParams; } | { pathname: `/app/tip5`; params?: Router.UnknownOutputParams; } | { pathname: `/app/constants/ThemeContext`; params?: Router.UnknownOutputParams; } | { pathname: `/app/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/app/fakecall${`?${string}` | `#${string}` | ''}` | `/app/home${`?${string}` | `#${string}` | ''}` | `/app${`?${string}` | `#${string}` | ''}` | `/app/login${`?${string}` | `#${string}` | ''}` | `/app/navigation${`?${string}` | `#${string}` | ''}` | `/app/profile${`?${string}` | `#${string}` | ''}` | `/app/safetytips${`?${string}` | `#${string}` | ''}` | `/app/signup${`?${string}` | `#${string}` | ''}` | `/app/sos${`?${string}` | `#${string}` | ''}` | `/app/tip1${`?${string}` | `#${string}` | ''}` | `/app/tip2${`?${string}` | `#${string}` | ''}` | `/app/tip3${`?${string}` | `#${string}` | ''}` | `/app/tip4${`?${string}` | `#${string}` | ''}` | `/app/tip5${`?${string}` | `#${string}` | ''}` | `/app/constants/ThemeContext${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/app/fakecall`; params?: Router.UnknownInputParams; } | { pathname: `/app/home`; params?: Router.UnknownInputParams; } | { pathname: `/app`; params?: Router.UnknownInputParams; } | { pathname: `/app/login`; params?: Router.UnknownInputParams; } | { pathname: `/app/navigation`; params?: Router.UnknownInputParams; } | { pathname: `/app/profile`; params?: Router.UnknownInputParams; } | { pathname: `/app/safetytips`; params?: Router.UnknownInputParams; } | { pathname: `/app/signup`; params?: Router.UnknownInputParams; } | { pathname: `/app/sos`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip1`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip2`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip3`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip4`; params?: Router.UnknownInputParams; } | { pathname: `/app/tip5`; params?: Router.UnknownInputParams; } | { pathname: `/app/constants/ThemeContext`; params?: Router.UnknownInputParams; } | `/app/+not-found` | { pathname: `/app/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
